version: "3.8"

services:
  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: safe_password
    volumes:
      - data_storage:/var/lib/mysql

  web_server:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - database

volumes:
  data_storage: